# Generated by Django 6.0.7 on 2026-07-13 18:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Bank name must contain only alphabets and spaces.', regex='^[A-Za-z ]+$')])),
                ('bank_code', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Bank code must contain exactly 4 uppercase letters.', regex='^[A-Z]{4}$')])),
                ('head_office', models.CharField(max_length=255)),
                ('customer_care_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, unique=True)),
                ('branch_code', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Branch code must contain exactly 4 digits.', regex='^\\d{4}$')])),
                ('ifsc_code', models.CharField(editable=False, max_length=11, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='PIN code must contain exactly 6 digits.', regex='^\\d{6}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='accounts.bank')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
                'ordering': ['bank', 'branch_name'],
                'constraints': [models.UniqueConstraint(fields=('bank', 'branch_name'), name='unique_branch_name_per_bank'), models.UniqueConstraint(fields=('bank', 'branch_code'), name='unique_branch_code_per_bank')],
            },
        ),
    ]
