# Generated by Django 6.0.7 on 2026-07-15 04:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Full name must contain only alphabets and spaces.', regex='^[A_Za-z ]+$')])),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Mobile number must contain exactly 10 digits.', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('identity_proof_type', models.CharField(max_length=50)),
                ('identity_id', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator(message='Identity ID must contain exactly 16 digits.', regex='^\\d{12}$')])),
                ('permanent_address', models.CharField(max_length=255)),
                ('permanent_city', models.CharField(max_length=100)),
                ('permanent_state', models.CharField(max_length=100)),
                ('permanent_pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='PIN code must contain exactly 6 digits.', regex='^\\d{6}$')])),
                ('current_address', models.CharField(blank=True, max_length=255)),
                ('current_city', models.CharField(blank=True, max_length=100)),
                ('current_state', models.CharField(blank=True, max_length=100)),
                ('current_pin_code', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='PIN code must contain exactly 6 digits.', regex='^\\d{6}$')])),
                ('address_proof_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='accounts.branch')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
