# Generated by Django 6.0.7 on 2026-07-17 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerapplication',
            name='application_id',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='customerapplication',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Full name must contain only alphabets and spaces.', regex='^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='customerapplication',
            name='identity_id',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Identity ID must contain exactly 16 digits.', regex='^\\d{12}$')]),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=14, unique=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='accounts.customerapplication')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='accounts.branch')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'customers',
                'db_table': 'customer',
                'ordering': ['customer_id'],
            },
        ),
    ]
