# Generated by Django 6.0.7 on 2026-07-19 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customerapplication_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_mobile',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Branch mobile number must contain exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
