# Generated by Django 6.0.7 on 2026-07-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_branch_branch_email_branch_branch_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['branch_code'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
    ]
