# Generated by Django 6.0.7 on 2026-07-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_branch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['bank', 'branch_code'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
    ]
