# Generated by Django 6.0.7 on 2026-07-19 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_branch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_email',
            field=models.EmailField(default='temp@pythonbank.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_mobile',
            field=models.CharField(default=4444441000, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Branch mobile number must contain exactly 10 digits.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
