# Generated by Django 6.0.7 on 2026-07-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customerapplication_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Application History'},
        ),
    ]
